eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservice: 
  etudiant-service:
    endpoints: 
      endpoint:
        uri: http://ETUDIANT-SERVICE/etudiants/ 
  enseignant-service:
    endpoints: 
      endpoint:
        uri: http://ENSEIGNANT-SERVICE/enseignants/ 
  cours-service:
    endpoints: 
      endpoint:
        uri: http://COURS-SERVICE/cours/
  etudiant-cours-service:
    endpoints: 
      endpoint:
        uri: http://ETUDIANT-COURS-SERVICE/etudiant-cours/ 
